//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class chatRole {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal chatRole() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Services.chatRole", typeof(chatRole).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我想让你充当dotnot方面的代码专家.
        /// </summary>
        public static string dotnet专家 {
            get {
                return ResourceManager.GetString("dotnet专家", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将中文翻译为英文，要专业请检查所有信息是否准确，并在回答时保持简洁，不需要任何其他反馈。.
        /// </summary>
        public static string 中翻英 {
            get {
                return ResourceManager.GetString("中翻英", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下面我让你来充当翻译家，你的目标是把任何语言翻译成中文。.
        /// </summary>
        public static string 英翻中 {
            get {
                return ResourceManager.GetString("英翻中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我想让你充当一个万能AI.
        /// </summary>
        public static string 通用 {
            get {
                return ResourceManager.GetString("通用", resourceCulture);
            }
        }
    }
}
