// <auto-generated />
using System;
using Database.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Database.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20211101082225_addDict")]
    partial class addDict
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("Database.Models.Component.Dict", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Audio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bnc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Collins")
                        .HasColumnType("TEXT");

                    b.Property<string>("Definition")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Exchange")
                        .HasColumnType("TEXT");

                    b.Property<string>("Frq")
                        .HasColumnType("TEXT");

                    b.Property<string>("Oxford")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phonetic")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pos")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .HasColumnType("TEXT");

                    b.Property<string>("Translation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Word")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Dicts");
                });

            modelBuilder.Entity("Database.Models.DoList.Thing", b =>
                {
                    b.Property<int>("ThingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Done")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FinishedTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Remind")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RemindTime")
                        .HasColumnType("TEXT");

                    b.HasKey("ThingId");

                    b.ToTable("Things");
                });
#pragma warning restore 612, 618
        }
    }
}
