// <auto-generated />
using System;
using Database.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(ContextLocal))]
    partial class ContextLocalModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("Database.Models.Component.DictDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Audio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bnc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Collins")
                        .HasColumnType("TEXT");

                    b.Property<string>("Definition")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Exchange")
                        .HasColumnType("TEXT");

                    b.Property<string>("Frq")
                        .HasColumnType("TEXT");

                    b.Property<string>("Oxford")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phonetic")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pos")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .HasColumnType("TEXT");

                    b.Property<string>("Translation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Word")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DictDbs");
                });

            modelBuilder.Entity("Database.Models.DoList.Thing", b =>
                {
                    b.Property<int>("ThingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreateTimeStamp")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Done")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FinishedTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Remind")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RemindTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdateTimeStamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("ThingId");

                    b.ToTable("Things");
                });
#pragma warning restore 612, 618
        }
    }
}
